--[[	
*** StableSnapshot ***
Written by : echomap
--]]

local L = LibStub("AceLocale-3.0"):GetLocale("StableSnapshot", false)

local StableSnapshotDB_defaults = {
	global = {
	}
}

StableSnapshot.DBSPELLS = {
	[ L["SpecialAbilities/Acid Spit"] ]            = { spellID=55749, text="Your worm spits acid, causing the enemy target to take an increased 4% physical damage for 25 sec.", castTime="Instant", cd="10seconds", range="30 yd" },
	[ L["SpecialAbilities/Ancient Hysteria"] ]     =  { spellID=90355, text="Increases melee, ranged, and spell casting speed by 30% for all party and raid members.  Lasts 40 sec.", castTime="Instant", cd="6min", range="" },
	[ L["SpecialAbilities/Ankle Crack"] ]          = { spellID=0, text="Snap at the target's feet, reducing movement speed by 50% for 6 sec.", castTime="Instant", cd="10sec", range="Melee" },		
	[ L["SpecialAbilities/Avoidance"] ]            = { spellID=0, text="Reduces the damage your pet takes from area of effect attacks by an additional 90%.", castTime="XX", cd="XX", range="XX" },		
	[ L["SpecialAbilities/Bad Manner"] ]           = { spellID=0, text="Hurls a handful of something special at the target, blinding them for 4 sec. Rude.", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Bellowing Roar"] ]       = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Bite"] ]                 = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Burrow Attack"] ]        = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Cackling Howl"] ]        = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Claw"] ]                 = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Clench"] ]               = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Cower"] ]                = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Demoralizing Roar"] ]    = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Demoralizing Screech"] ] = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Dust Cloud"] ]           = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Embrace of the Shale Spider"] ] = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Eternal Guardian"] ]     = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Fearless Roar"] ]        = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Fire Breath"] ]          = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Frost Breath"] ]         = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Froststorm Breath"] ]    = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Furious Howl"] ]         = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Gore"] ]                 = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Growl"] ]                = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Harden Carapace"] ]      = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Horn Toss"] ]            = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Lava Breath"] ]          = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Lightning Breath"] ]     = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Lock Jaw"] ]             = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Lullaby"] ]              = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Monstrous Bite"] ]       = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },	
	[ L["SpecialAbilities/Nether Shock"] ]         = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },		
	[ L["SpecialAbilities/Paralyzing Quill"] ]     = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },		
	[ L["SpecialAbilities/Petrifying Gaze"] ]      = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },		
	[ L["SpecialAbilities/Pin"] ]                  = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },		
	[ L["SpecialAbilities/Play"] ]                 = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },		
	[ L["SpecialAbilities/Prowl"] ]                = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },		
	[ L["SpecialAbilities/Pummel"] ]               = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Qiraji Fortitude"] ]     = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Ravage"] ]               = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Rest"] ]                 = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Roar of Courage"] ]      = { spellID=93435, text="xxx", castTime="Instant", cd="45seconds", range="" },
	[ L["SpecialAbilities/Serenity Dust"] ]        = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Serpent's Swiftness"] ]  = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Shell Shield"] ]         = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Smack"] ]                = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Snatch"] ]               = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Sonic Blast"] ]          = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Spirit Beast Blessing"] ]= { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Spirit Mend"] ]          = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Spirit Walk"] ]          = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Spore Cloud"] ]          = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Stampede"] ]             = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Still Water"] ]          = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Sting"] ]                = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Surface Trot"] ]         = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Tailspin"] ]             = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Tear Armor"] ]           = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Terrifying Roar"] ]      = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Time Warp"] ]            = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Trample"] ]              = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Trick"] ]                = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Venom Web Spray"] ]      = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Web"] ]                  = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Web Wrap"] ]             = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" },
	[ L["SpecialAbilities/Unknown"] ]              = { spellID=0, text="XXX", castTime="XX", cd="XX", range="XX" }
}

StableSnapshot.DBDefaults2 = {
    [ L["PetFamilies/Bat"]]            = { DefaultSpec=L["PetMisc/Cunning"],  SpecialAbility=L["SpecialAbilities/Sonic Blast"] },
    [ L["PetFamilies/Bird of Prey"]]   = { DefaultSpec=L["PetMisc/Cunning"],  SpecialAbility=L["SpecialAbilities/Snatch"],                CanTrick=true },
    [ L["PetFamilies/Chimaera"]]       = { DefaultSpec=L["PetMisc/Cunning"],  SpecialAbility=L["SpecialAbilities/Frost Breath"],          Exotic=true, ExoticAbility=L["SpecialAbilities/Froststorm Breath"] },
    [ L["PetFamilies/Crane"]]          = { DefaultSpec=L["PetMisc/Cunning"],  SpecialAbility=L["SpecialAbilities/Lullaby"],               CanTrick=true },
    [ L["PetFamilies/Dragonhawk"]]     = { DefaultSpec=L["PetMisc/Cunning"],  SpecialAbility=L["SpecialAbilities/Fire Breath"] },
    [ L["PetFamilies/Monkey"]]         = { DefaultSpec=L["PetMisc/Cunning"],  SpecialAbility=L["SpecialAbilities/Bad Manners"] },
    [ L["PetFamilies/Nether Ray"]]     = { DefaultSpec=L["PetMisc/Cunning"],  SpecialAbility=L["SpecialAbilities/Nether Shock"] },
    [ L["PetFamilies/Ravager"] ]       = { DefaultSpec=L["PetMisc/Cunning"],  SpecialAbility=L["SpecialAbilities/Ravage"] },
    [ L["PetFamilies/Serpent"] ]       = { DefaultSpec=L["PetMisc/Cunning"],  SpecialAbility=L["SpecialAbilities/Serpent's Swiftness"] },
    [ L["PetFamilies/Silithid"] ]      = { DefaultSpec=L["PetMisc/Cunning"],  SpecialAbility=L["SpecialAbilities/Venom Web Spray"],       Exotic=true, ExoticAbility=L["SpecialAbilities/Qiraji Fortitude"] },
    [ L["PetFamilies/Spider"] ]        = { DefaultSpec=L["PetMisc/Cunning"],  SpecialAbility=L["SpecialAbilities/Web"] },
    [ L["PetFamilies/Sporebat"] ]      = { DefaultSpec=L["PetMisc/Cunning"],  SpecialAbility=L["SpecialAbilities/Spore Cloud"] },
    [ L["PetFamilies/Water Strider"] ] = { DefaultSpec=L["PetMisc/Cunning"],  SpecialAbility=L["SpecialAbilities/Surface Trot"],          Exotic=true, ExoticAbility=L["SpecialAbilities/Still Water"] },
    [ L["PetFamilies/Wind Serpent"] ]  = { DefaultSpec=L["PetMisc/Cunning"],  SpecialAbility=L["SpecialAbilities/Lightning Breath"] },
    [ L["PetFamilies/Carrion Bird"] ]  = { DefaultSpec=L["PetMisc/Ferocity"], SpecialAbility=L["SpecialAbilities/Demoralizing Screech"] },
    [ L["PetFamilies/Cat"] ]           = { DefaultSpec=L["PetMisc/Ferocity"], SpecialAbility=L["SpecialAbilities/Roar of Courage"],       CanProwl=true },
    [ L["PetFamilies/Core Hound"] ]    = { DefaultSpec=L["PetMisc/Ferocity"], SpecialAbility=L["SpecialAbilities/Lava Breath"],           Exotic=true, ExoticAbility=L["SpecialAbilities/Ancient Hysteria"] },
    [ L["PetFamilies/Devilsaur"] ]     = { DefaultSpec=L["PetMisc/Ferocity"], SpecialAbility=L["SpecialAbilities/Terrifying Roar"],       Exotic=true, ExoticAbility=L["SpecialAbilities/Monstrous Bite"] },
    [ L["PetFamilies/Dog"] ]           = { DefaultSpec=L["PetMisc/Ferocity"], SpecialAbility=L["SpecialAbilities/Lock Jaw"] },
    [ L["PetFamilies/Fox"] ]           = { DefaultSpec=L["PetMisc/Ferocity"], SpecialAbility=L["SpecialAbilities/Tailspin"],              CanPlay=true },
    [ L["PetFamilies/Goat"] ]          = { DefaultSpec=L["PetMisc/Ferocity"], SpecialAbility=L["SpecialAbilities/Trample"] },
    [ L["PetFamilies/Hydra"] ]         = { DefaultSpec=L["PetMisc/Ferocity"], SpecialAbility=L["SpecialAbilities/Bellowing Roar"],        Untamable=true },
    [ L["PetFamilies/Hyena"] ]         = { DefaultSpec=L["PetMisc/Ferocity"], SpecialAbility=L["SpecialAbilities/Cackling Howl"] },
    [ L["PetFamilies/Moth"] ]          = { DefaultSpec=L["PetMisc/Ferocity"], SpecialAbility=L["SpecialAbilities/Serenity Dust"] },
    [ L["PetFamilies/Quilen"] ]        = { DefaultSpec=L["PetMisc/Ferocity"], SpecialAbility=L["SpecialAbilities/Fearless Roar"],         Exotic=true, ExoticAbility=L["SpecialAbilities/Eternal Guardian" ] },
    [ L["PetFamilies/Raptor"] ]        = { DefaultSpec=L["PetMisc/Ferocity"], SpecialAbility=L["SpecialAbilities/Tear Armor"] },
    [ L["PetFamilies/Spirit Beast"] ]  = { DefaultSpec=L["PetMisc/Ferocity"], SpecialAbility=L["SpecialAbilities/Spirit Beast Blessing"], Exotic=true, ExoticAbility=L["SpecialAbilities/Spirit Mend"], CanProwl=true },
    [ L["PetFamilies/Tallstrider"] ]   = { DefaultSpec=L["PetMisc/Ferocity"], SpecialAbility=L["SpecialAbilities/Dust Cloud"] },
    [ L["PetFamilies/Wasp"] ]          = { DefaultSpec=L["PetMisc/Ferocity"], SpecialAbility=L["SpecialAbilities/Sting"] },
    [ L["PetFamilies/Wolf"] ]          = { DefaultSpec=L["PetMisc/Ferocity"], SpecialAbility=L["SpecialAbilities/Furious Howl"] },
    [ L["PetFamilies/Basilisk"] ]      = { DefaultSpec=L["PetMisc/Tenacity"], SpecialAbility=L["SpecialAbilities/Petrifying Gaze"] },
    [ L["PetFamilies/Bear"] ]          = { DefaultSpec=L["PetMisc/Tenacity"], SpecialAbility=L["SpecialAbilities/Demoralizing Roar"],     CanRest=true },
    [ L["PetFamilies/Beetle"] ]        = { DefaultSpec=L["PetMisc/Tenacity"], SpecialAbility=L["SpecialAbilities/Harden Carapace"] },
    [ L["PetFamilies/Boar"] ]          = { DefaultSpec=L["PetMisc/Tenacity"], SpecialAbility=L["SpecialAbilities/Gore"] },
    [ L["PetFamilies/Crab"] ]          = { DefaultSpec=L["PetMisc/Tenacity"], SpecialAbility=L["SpecialAbilities/Pin"] },
    [ L["PetFamilies/Crocolisk"] ]     = { DefaultSpec=L["PetMisc/Tenacity"], SpecialAbility=L["SpecialAbilities/Ankle Crack"] },
    [ L["PetFamilies/Gorilla"] ]       = { DefaultSpec=L["PetMisc/Tenacity"], SpecialAbility=L["SpecialAbilities/Pummel"] },
    [ L["PetFamilies/Porcupine"] ]     = { DefaultSpec=L["PetMisc/Tenacity"], SpecialAbility=L["SpecialAbilities/Paralyzing Quill"],      CanRest=true },
    [ L["PetFamilies/Rhino"] ]         = { DefaultSpec=L["PetMisc/Tenacity"], SpecialAbility=L["SpecialAbilities/Stampede"],              Exotic=true, ExoticAbility=L["SpecialAbilities/Horn Toss"] },
    [ L["PetFamilies/Scorpid"] ]       = { DefaultSpec=L["PetMisc/Tenacity"], SpecialAbility=L["SpecialAbilities/Clench"] },
    [ L["PetFamilies/Shale Spider"] ]  = { DefaultSpec=L["PetMisc/Tenacity"], SpecialAbility=L["SpecialAbilities/Web Wrap"],              Exotic=true, ExoticAbility=L["SpecialAbilities/Embrace of the Shale Spider"] },
    [ L["PetFamilies/Turtle"] ]        = { DefaultSpec=L["PetMisc/Tenacity"], SpecialAbility=L["SpecialAbilities/Shell Shield"] },
    [ L["PetFamilies/Warp Stalker"] ]  = { DefaultSpec=L["PetMisc/Tenacity"], SpecialAbility=L["SpecialAbilities/Time Warp"] },
    [ L["PetFamilies/Worm"] ]          = { DefaultSpec=L["PetMisc/Tenacity"], SpecialAbility=L["SpecialAbilities/Acid Spit"],             Exotic=true, ExoticAbility=L["SpecialAbilities/Burrow Attack"] }
}
